name: Codacy Coverage Reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: flatter_user
          POSTGRES_PASSWORD: flatter_password
          POSTGRES_DB: flatter_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Run migrations
        run: |
          cd backend
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate
      - name: Run tests and coverage
        run: |
          cd backend
          coverage run manage.py test
          coverage xml
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: backend/coverage.xml
          # or a comma-separated list for multiple reports
          # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>