name: Development Flatter Deployment

on:
  push:
    branches:
      - develop

env:
  PROJECT_ID: "flatter-378818"
  GKE_CLUSTER: flatter-cluster-dev
  GKE_ZONE: europe-west9

jobs:
  flatter-dev-deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        project_id: "${{ env.PROJECT_ID }}"
        workload_identity_provider: 'principal://iam.googleapis.com/projects/flatter-378818/locations/global/workloadIdentityPools/default/*'
        service_account: '737052749385-compute@developer.gserviceaccount.com'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Deploy
      run: |-
        kubectl get nodes